### ISSUE TITLE
Figure out Twitter Auth and begin implementation

### ISSUE THREAD

**Issue by erin2722** [MLH-Fellowship/0.2.1-donation-trigger#5]
If twitter does not work, look into Instagram

**Comment by barronwei** [comment]
Perhaps we could get an [OAuth token](https://developer.twitter.com/en/docs/basics/authentication/oauth-2-0) from Twitter and store that as a cookie on our site.

**Comment by cedricgrothues** [comment]
Looks like I can't use the `Filtered Stream` API because too many people use it already.
Not sure if there is another endpoint for filtering tweets based on their hashtags.

![Screen Shot 2020-06-02 at 21 11 22](https://user-images.githubusercontent.com/34948511/83559966-b94dc780-a515-11ea-9a5c-cb8563aa0829.png)

**Comment by barronwei** [comment]
One alternative that comes to mind is scraping, but that sounds painful.
